### PR TITLE
Hotfix desktopserver

### PR DESCRIPTION
**Pull request by afragen**
It's great that Airplane Mode is included in DesktopServer 3.8, but a fatal can occur if you are also using it in your test env. Probably better to exclude possibility of a fatal.

Also fixed a small typo in the AIRMDE_BASE constant check and added a .gitattributes file to not include certain files during update.

A new tag will be needed for the update to occur.

### CODE REVIEW

**Comment by norcross** [comment]
good catch @afragen

**Comment by afragen** [comment]
That large fatal on my local env made the catch pretty easy. :wink:

**Comment by afragen** [comment]
Should probably get the ServerPress folks to include this update in DesktopServer.

**Comment by norcross** [comment]
I'm updating the Composer support part so that may handle it.

**Comment by Steveorevo** [comment]
Thanks for the heads up; great work!

**Comment by norcross** [comment]
@Steveorevo if there's anything else on my end that'll help keep the integration with DesktopServer working smoothly let me know.

**Pull request merged**
