### PR TITLE
Updated min.css and removed execution bit

### PR DESCRIPTION
**Pull request by szepeviktor**
min.css was outdated.
Everyone has `SCRIPT_DEBUG` on?

### CODE REVIEW

**Comment by norcross** [comment]
I actually have another minor CSS fix coming as well, but given the amount of updates I did yesterday I wanted to give it some pause.

as for the other issue, not sure what you mean. most people would have `SCRIPT_DEBUG` on during development but not all.

**Comment by szepeviktor** [comment]
When you have `SCRIPT_DEBUG` on, you don't notice the outdated min.css.

**Comment by norcross** [comment]
fixed this in https://github.com/norcross/airplane-mode/commit/80268f2753e87027b14029dbf62d534c4681c83b

**Comment by szepeviktor** [comment]
Please fix the execution bit also.

**Comment by norcross** [comment]
I don't know what that is referring to. the file diff shows no changes.

**Comment by szepeviktor** [comment]
CLick here: [File mode changed ](https://github.com/norcross/airplane-mode/pull/50/files)

**Comment by norcross** [comment]
I see it says that. but what is the file mode and what is changing?

**Comment by szepeviktor** [comment]
This is my video reply: http://youtu.be/cGNDjao77O0

**Comment by norcross** [comment]
ok, I follow now. let me get the pending PR done later this morning, then can you submit a separate PR with just that fix?

**Comment by norcross** [comment]
@szepeviktor I've committed the pending change. please submit a new PR for the file mode issue, then I'll do a version bump for updates

**Pull request closed without merging**
