### PR TITLE
HTTP request counter

### PR DESCRIPTION
**Pull request by szepeviktor**
Please note: `airplane-mode.php 100755 → 100644`

### CODE REVIEW

**Comment by szepeviktor** [comment]
air-pic

**Comment by szepeviktor** [comment]
If it is OK, please add one line to the readme.

**Comment by szepeviktor** [comment]
@norcross If it is OK, please add one line about this feature to the readme.

**Comment by szepeviktor** [comment]
Is it more WP-like?

```html
<span class="update-plugins count-5">
    <span class="plugin-count">5</span>
</span>
```

**Comment by joeguilmette** [comment]
If you enable Airplane Mode and view the plugins page it comes up with 0. With Airplane Mode disabled, it displays a non-zero number of requests on the plugins page.

**Comment by norcross** [comment]
I had another large merge, so I couldn't merge this directly, but I am adding it into the upcoming commit

**Comment by szepeviktor** [comment]
Is the "upcoming commit" in an issue?

**Comment by szepeviktor** [comment]
Here it is: https://github.com/norcross/airplane-mode/commit/aa7ea1951853af9dc87858825ae074a327ff651c

**Pull request closed without merging**
