### PR TITLE
redirect from update-core.php

### PR DESCRIPTION
**Pull request by afragen**
if airplane mode activated while on update-core.php a die permissions issue page results.

This fixes the issue I described during coffee.

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
Still coffee time?

**Comment by afragen** [comment]
It's always :coffee: time, but @norcross has final say.

**Comment by franz-josef-kaiser** [comment]
@norcross Ok, mate. Either you merge this, or you buy a ticket here to Vienna and I get you some more :coffee: (and :beers: ) to get you motivated for a merge.

**Comment by afragen** [comment]
Actually, I think I misplaced this code. I'm going to update to put into `Airplane_Mode::get_redirect()`. It's probably a better fit there.

**Comment by afragen** [comment]
There, I think that looks to be in a better method. Function should be identical.

**Comment by norcross** [comment]
I did a bunch of cleanup for WPCS items and whatnot before I saw this. So I'm going to add it into my next merge.

**Comment by afragen** [comment]
Sounds good

**Comment by afragen** [comment]
So where does this develop branch exist? :smiling_imp:

**Pull request closed without merging**
