### PR TITLE
Block remote stylesheets from themes and plugins

### PR DESCRIPTION
**Pull request by iandunn**
Previously, only Core's default stylesheets were blocked, so remote stylesheets from themes and plugins would still load. For example, the Merriweather web font from the TwentySixteen theme.

This may not be ready to merge, but it's a start.

1) I removed the `airplane_mode_style_load` action because it didn't seem like it was useful for the intended purpose, since it's not a filter and `$registered` wasn't passed by reference, so the callback wouldn't have any way of modifying the value. I could be missing something there, though.

2) If the filter should be preserved, we'll probably want a way to preserve backwards-compatibility. I don't see a good way to do that at the moment, though.

3) If we do this for styles, we should probably also do it for scripts. That could be a separate PR, though.

### CODE REVIEW

**Comment by iandunn** [comment]
It looks like #62 intended to do this, but it only works for Core because it's using `wp_default_styles`, which doesn't include plugins and themes.

**Comment by norcross** [comment]
I like this. Lemme throw some edge cases at it and see if it hits all the various issues that came up when I wrote the original function.

**Comment by norcross** [comment]
I'm implementing your idea for both the JS and CSS loading. I'm closing this PR because I've implemented it for both functions (along with an unrelated fix)

**Comment by iandunn** [comment]
Awesome, thanks :)

**Pull request closed without merging**
