### PR TITLE
Remove one indent

### PR DESCRIPTION
**Pull request by szepeviktor**
@norcross One less indent: bail out early.

Easy review: https://github.com/norcross/airplane-mode/pull/114/files?diff=unified&w=1

### CODE REVIEW

**Comment by norcross** [comment]
has this been like that the whole time? it seems like this change turns on or off opposite of what it's doing now.

**Comment by szepeviktor** [comment]
The original condition was `$this->enabled()`, I've changed it to `! $this->enabled()` and added `return`. So when the airplane mode is not enabled it stops the constructor.

**Comment by szepeviktor** [comment]
Like here
https://github.com/norcross/airplane-mode/blob/ba64ab53cf2666132055fb2e34ee7a73b2ca137f/airplane-mode.php#L954-L957

**Comment by norcross** [comment]
i'm going to handle all your PR's against `develop` then do one larger PR to `main` and release

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
