### PR TITLE
fix for add plugin page

### PR DESCRIPTION
**Pull request by afragen**
last bit of CSS hides the plugin installation header even when Airplane Mode is disabled but activated.

### CODE REVIEW

**Comment by afragen** [comment]
Let me clean this up

**Comment by afragen** [comment]
OK, now it's cleaned up.

**Comment by norcross** [comment]
@afragen  instead of a second CSS file, why not just add a body class on the admin when active, then target that?

**Comment by afragen** [comment]
I think I understand. Let me give that a whirl.

**Comment by norcross** [comment]
ok. ill close this one, since I'm about to add some other CSS (unrelated).

**Pull request closed without merging**
