### PR TITLE
WordCamp San Diego Work

### PR DESCRIPTION
**Pull request by chriscct7**
Here's a list of the things this fixes:
- Blocks all calls for updates for WordPress core, plugins, themes and translations
- Removes calls to WordPress.org to get theme and plugin information
- Removes calls to WordPress.org to get available translations
- Removes calls to WordPress.org to get favorite, new, popular etc themes and plugins as well as the tags and categories of them
- Improves the add plugin page by only showing the update form and literally nothing else
- Improves the add theme page by only showing the add theme button, and removing the extra browse  themes button
- Removes the plugin view details row as well as the update actions

### CODE REVIEW

**Comment by norcross** [comment]
you wrapped all the new functions inside the Jetpack enabled setup

**Comment by chriscct7** [comment]
@norcross I don't think I did, I wrapped it inside of $this->enabled to only fire if Airplane mode is enabled. Forgot to remove an extra comment.

**Comment by norcross** [comment]
Its working for me, but there will be some formatting changes

**Comment by chriscct7** [comment]
Duly noted. Thanks!

**Pull request merged**
