### PR TITLE
Use icon font for toolbar icon, remove label

### PR DESCRIPTION
**Pull request by barryceelen**
An attempt at making the toolbar item a better WordPress citizen.
In stead of the .png icon a custom icon font is added. Also boldly removes the status label.

### CODE REVIEW

**Comment by norcross** [comment]
can you put a screenshot here of the difference?

**Comment by barryceelen** [comment]
pasted_image_10_04_16_04_07

Sure! Bottom images illustrate hover state on default theme, and coloured icon on the light theme.

**Comment by barryceelen** [comment]
On closer inspection it seems I didn’t get the direction of the disabled icon’s slash right.
Should go from top left to bottom right:
pasted_image_10_04_16_04_24

**Comment by norcross** [comment]
just a heads up, I've been traveling for the last week and haven't had solid internet, so I'm going to look at this next week when I'm home with a solid connection.

**Comment by barryceelen** [comment]
👍

**Comment by norcross** [comment]
I noticed that the new body class wasn't being applied on the front-end, only the back end. So I'm modifying this PR and will commit it myself, but props will still go to you.

**Comment by barryceelen** [comment]
Thanks!

**Pull request closed without merging**
